# Generated by Django 5.1.3 on 2025-06-03 17:00

import django.db.models.deletion
import private_watchers.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoverSubdomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('subdomain', models.CharField(blank=True, max_length=300, null=True)),
                ('label', models.CharField(choices=[('new', 'NEW'), ('available', 'AVAILABLE')], default='new', max_length=50)),
            ],
            options={
                'verbose_name': 'Discovered Subdomain',
                'verbose_name_plural': 'Discovered Subdomains',
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(choices=[('owned', 'Owned'), ('amass', 'Amass'), ('subfinder', 'Subfinder'), ('dns_bruteforce', 'DNS Bruteforce'), ('httpx', 'Httpx'), ('wabackurls', 'Wabackurls'), ('crt.sh', 'CRT.sh')], default='subfinder', max_length=120)),
            ],
            options={
                'verbose_name': 'Tool',
                'verbose_name_plural': 'Tools',
            },
        ),
        migrations.CreateModel(
            name='AssetWatcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notify', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=150)),
                ('dns_bruteforce_wordlist', models.FileField(blank=True, default=private_watchers.models.default_wordlist_path, null=True, upload_to=private_watchers.models.user_static_wordlist_upload_path, validators=[private_watchers.models.validate_wordlist_file])),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asset Watcher',
                'verbose_name_plural': 'Asset Watchers',
            },
        ),
        migrations.CreateModel(
            name='JSFileWatcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=150)),
                ('notify', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'JSFileWatcher',
                'verbose_name_plural': 'JSFileWatchers',
            },
        ),
        migrations.CreateModel(
            name='JSFileWatchList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=150)),
                ('jsfilewatcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='private_watchers.jsfilewatcher')),
            ],
            options={
                'verbose_name': 'JSFileWatchList',
                'verbose_name_plural': 'JSFileWatchLists',
            },
        ),
        migrations.CreateModel(
            name='SubdomainHttpx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('httpx_result', models.URLField(blank=True, max_length=300, null=True)),
                ('status_code', models.CharField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('server', models.CharField(blank=True, max_length=300, null=True)),
                ('technologies', models.CharField(blank=True, max_length=900)),
                ('has_ssl', models.CharField(default='False')),
                ('ip_address', models.CharField(blank=True, max_length=120, null=True)),
                ('port', models.CharField(blank=True, null=True)),
                ('content_type', models.CharField(blank=True, max_length=300, null=True)),
                ('content_length', models.IntegerField(blank=True, null=True)),
                ('cname', models.CharField(blank=True)),
                ('a_records', models.CharField(blank=True)),
                ('label', models.CharField(choices=[('new', 'NEW'), ('available', 'AVAILABLE')], default='new')),
                ('discovered_subdomain', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='private_watchers.discoversubdomain')),
            ],
            options={
                'verbose_name': 'Subdomain Httpx',
                'verbose_name_plural': 'Subdomain Httpxes',
            },
        ),
        migrations.CreateModel(
            name='SubdomainHttpxChanges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('httpx_result_change', models.CharField(blank=True, null=True)),
                ('status_code_change', models.CharField(blank=True, null=True)),
                ('title_change', models.CharField(blank=True, max_length=500, null=True)),
                ('server_change', models.CharField(blank=True, null=True)),
                ('technologies_change', models.CharField(blank=True)),
                ('has_ssl_change', models.CharField(default='False')),
                ('ip_address_change', models.CharField(blank=True, null=True)),
                ('port_change', models.CharField(blank=True, null=True)),
                ('content_type_change', models.CharField(blank=True, null=True)),
                ('content_length_change', models.CharField(blank=True, null=True)),
                ('cname_change', models.CharField(blank=True)),
                ('a_records_change', models.CharField(blank=True)),
                ('label', models.CharField(choices=[('new', 'NEW'), ('available', 'AVAILABLE')], default='new')),
                ('discovered_subdomain', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='private_watchers.discoversubdomain')),
            ],
            options={
                'verbose_name': 'Subdomain Httpx Changes',
                'verbose_name_plural': 'Subdomain Httpxes Changes',
            },
        ),
        migrations.AddField(
            model_name='discoversubdomain',
            name='tool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='private_watchers.tool'),
        ),
        migrations.CreateModel(
            name='WatchedJSFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('file_url', models.URLField(max_length=150)),
                ('current_hash', models.CharField(blank=True, max_length=150, null=True)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('has_changed', models.BooleanField(default=False)),
                ('jsfilewatchlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='private_watchers.jsfilewatchlist')),
            ],
            options={
                'verbose_name': 'WatchedJSFile',
                'verbose_name_plural': 'WatchedJSFiles',
            },
        ),
        migrations.CreateModel(
            name='WatchedJSFileChanged',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('old_hash', models.CharField(max_length=150, null=True)),
                ('new_hash', models.CharField(max_length=150, null=True)),
                ('diff_snipped', models.CharField(max_length=150, null=True)),
                ('changed_at', models.DateTimeField(blank=True, null=True)),
                ('watchedjsfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='private_watchers.watchedjsfile')),
            ],
            options={
                'verbose_name': 'WatchedJSFileChanged',
                'verbose_name_plural': 'WatchedJSFileChangeds',
            },
        ),
        migrations.CreateModel(
            name='WatchedWildcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('wildcard', models.CharField(blank=True, max_length=300, null=True)),
                ('own_subdomains', models.FileField(blank=True, null=True, upload_to=private_watchers.models.user_subdomains_upload_path, validators=[private_watchers.models.validate_wordlist_file])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=150)),
                ('tools', models.ManyToManyField(to='private_watchers.tool')),
                ('watcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wildcards', to='private_watchers.assetwatcher')),
            ],
            options={
                'verbose_name': 'Watched Wildcard',
                'verbose_name_plural': 'Watcher Wildcards',
            },
        ),
        migrations.AddField(
            model_name='discoversubdomain',
            name='wildcard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdomains', to='private_watchers.watchedwildcard'),
        ),
    ]
