# Generated by Django 5.1.3 on 2025-06-03 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_watchers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subdomainhttpxchanges',
            old_name='content_length_change',
            new_name='body_hash_change',
        ),
        migrations.RemoveField(
            model_name='subdomainhttpx',
            name='cname',
        ),
        migrations.RemoveField(
            model_name='subdomainhttpx',
            name='content_length',
        ),
        migrations.RemoveField(
            model_name='subdomainhttpx',
            name='has_ssl',
        ),
        migrations.RemoveField(
            model_name='subdomainhttpxchanges',
            name='cname_change',
        ),
        migrations.RemoveField(
            model_name='subdomainhttpxchanges',
            name='has_ssl_change',
        ),
        migrations.AddField(
            model_name='subdomainhttpx',
            name='body_hash',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='subdomainhttpx',
            name='has_cdn',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subdomainhttpx',
            name='header_hash',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='subdomainhttpx',
            name='line_count',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subdomainhttpxchanges',
            name='has_cdn_change',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subdomainhttpxchanges',
            name='header_hash_change',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subdomainhttpxchanges',
            name='line_count_change',
            field=models.CharField(blank=True, null=True),
        ),
    ]
