# Generated by Django 5.1.3 on 2025-06-04 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('private_watchers', '0002_rename_content_length_change_subdomainhttpxchanges_body_hash_change_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetwatcher',
            old_name='dns_bruteforce_wordlist',
            new_name='dns_bruteforce_static_wordlist',
        ),
    ]
