# Generated by Django 5.1.3 on 2025-06-04 17:04

import private_watchers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_watchers', '0003_rename_dns_bruteforce_wordlist_assetwatcher_dns_bruteforce_static_wordlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetwatcher',
            name='dns_bruteforce_dynamic_wordlist',
            field=models.FileField(blank=True, default=private_watchers.models.default_wordlist_path, null=True, upload_to=private_watchers.models.user_dynamic_wordlist_upload_path, validators=[private_watchers.models.validate_wordlist_file]),
        ),
    ]
