# Generated by Django 5.1.3 on 2025-06-05 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_watchers', '0004_assetwatcher_dns_bruteforce_dynamic_wordlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jsfilewatcher',
            name='user',
        ),
        migrations.AddField(
            model_name='jsfilewatcher',
            name='watcher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jsfiles', to='private_watchers.assetwatcher'),
        ),
    ]
