# Generated by Django 5.1.3 on 2025-06-05 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_watchers', '0005_remove_jsfilewatcher_user_jsfilewatcher_watcher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watchedwildcard',
            options={'verbose_name': 'Watcher Wildcard', 'verbose_name_plural': 'Watcher Wildcards'},
        ),
        migrations.CreateModel(
            name='WatcherCIDR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('cidr', models.CharField(blank=True, max_length=50, null=True)),
                ('label', models.CharField(choices=[('new', 'NEW'), ('available', 'AVAILABLE')], default='new', max_length=50)),
                ('watcher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cidrs', to='private_watchers.assetwatcher')),
            ],
            options={
                'verbose_name': 'Watcher CIDR',
                'verbose_name_plural': 'Watcher CIDRs',
            },
        ),
    ]
