# Generated by Django 5.1.3 on 2025-06-05 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_watchers', '0006_alter_watchedwildcard_options_watchercidr'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchercidr',
            name='ports',
            field=models.CharField(blank=True, choices=[('80', '80'), ('8080', '8080'), ('8081', '8081'), ('8880', '8880'), ('2052', '2052'), ('2082', '2082'), ('2086', '2086'), ('2095', '2095'), ('443', '443'), ('2053', '2053'), ('2087', '2087'), ('2096', '2096'), ('8443', '8443'), ('10443', '10443')], max_length=10, null=True),
        ),
    ]
