# Generated by Django 5.1.3 on 2025-06-05 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_watchers', '0007_watchercidr_ports'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.CharField(blank=True, choices=[('80', '80'), ('8080', '8080'), ('8081', '8081'), ('8880', '8880'), ('2052', '2052'), ('2082', '2082'), ('2086', '2086'), ('2095', '2095'), ('443', '443'), ('2053', '2053'), ('2087', '2087'), ('2096', '2096'), ('8443', '8443'), ('10443', '10443')], max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Port',
                'verbose_name_plural': 'Ports',
            },
        ),
        migrations.RemoveField(
            model_name='watchercidr',
            name='ports',
        ),
        migrations.AddField(
            model_name='watchercidr',
            name='ports',
            field=models.ManyToManyField(to='private_watchers.ports'),
        ),
    ]
