# Generated by Django 5.1.3 on 2025-06-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_watchers', '0008_ports_remove_watchercidr_ports_watchercidr_ports'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchercidr',
            name='label',
        ),
        migrations.AddField(
            model_name='watchercidr',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='new', max_length=50),
        ),
    ]
