# Generated by Django 5.1.3 on 2025-06-05 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_watchers', '0009_remove_watchercidr_label_watchercidr_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoverdServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ip', models.CharField(blank=True, max_length=20, null=True)),
                ('port', models.CharField(blank=True, max_length=10, null=True)),
                ('service', models.CharField(blank=True, max_length=20, null=True)),
                ('has_service', models.BooleanField(default=False)),
                ('label', models.CharField(choices=[('new', 'NEW'), ('available', 'AVAILABLE')], default='available')),
                ('watcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discoverd_services', to='private_watchers.watchercidr')),
            ],
            options={
                'verbose_name': 'Discoverd Service',
                'verbose_name_plural': 'Discovered Services',
            },
        ),
    ]
