# Generated by Django 5.1.3 on 2025-06-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_watchers', '0010_discoverdservices'),
    ]

    operations = [
        migrations.AddField(
            model_name='discoverdservices',
            name='has_change',
            field=models.BooleanField(default=False),
        ),
    ]
