# Generated by Django 5.1.3 on 2025-06-05 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_watchers', '0011_discoverdservices_has_change'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discoverdservices',
            name='has_service',
        ),
        migrations.RemoveField(
            model_name='discoverdservices',
            name='service',
        ),
        migrations.CreateModel(
            name='DiscoverdServicesAlive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('service', models.CharField(blank=True, max_length=20, null=True)),
                ('status_code', models.CharField(blank=True, max_length=100, null=True)),
                ('label', models.CharField(choices=[('new', 'NEW'), ('available', 'AVAILABLE')], default='available')),
                ('watcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discoverd_services_alive', to='private_watchers.watchercidr')),
            ],
            options={
                'verbose_name': 'Discovered Service Alive',
                'verbose_name_plural': 'Discovered Services Alive',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
