# Generated by Django 5.1.3 on 2025-06-05 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_watchers', '0012_remove_discoverdservices_has_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discoverdservicesalive',
            name='service',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
