# Generated by Django 5.2.4 on 2025-07-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_watchers', '0013_alter_discoverdservicesalive_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdomainhttpx',
            name='has_cdn',
            field=models.CharField(default='False'),
        ),
    ]
