# Generated by Django 5.2.4 on 2025-07-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_watchers', '0014_alter_subdomainhttpx_has_cdn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdomainhttpx',
            name='has_cdn',
            field=models.CharField(blank=True, default='False', max_length=10, null=True),
        ),
    ]
