# Generated by Django 5.2.4 on 2025-07-20 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_watchers', '0015_alter_subdomainhttpx_has_cdn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchedwildcard',
            name='wildcard',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='watchercidr',
            name='cidr',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
