# Generated by Django 5.2.4 on 2025-07-20 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_watchers', '0016_alter_watchedwildcard_wildcard_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchedwildcard',
            name='wildcard',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
