# Generated by Django 5.2.4 on 2025-07-20 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_watchers', '0017_alter_watchedwildcard_wildcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchercidr',
            name='cidr',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
