# Generated by Django 5.2.4 on 2025-08-02 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_watchers', '0019_alter_watchedwildcard_wildcard_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discoversubdomain',
            name='subdomain',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True),
        ),
    ]
