# Generated by Django 5.2.4 on 2025-08-06 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_watchers', '0022_alter_tool_tool_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='tool_name',
            field=models.CharField(choices=[('owned', 'Owned'), ('amass', 'Amass'), ('subfinder', 'Subfinder'), ('dns_bruteforce', 'DNS Bruteforce'), ('httpx', 'Httpx'), ('wabackurls', 'Wabackurls'), ('crt.sh', 'CRT.sh'), ('shodan', 'Shodan')], default='subfinder', max_length=120),
        ),
    ]
