# Generated by Django 5.2.4 on 2025-08-16 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asset_monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('url', models.CharField(max_length=300)),
                ('label', models.CharField(choices=[('new', 'NEW'), ('available', 'AVAILABLE')], default='new', max_length=150)),
                ('ext', models.CharField(choices=[('none', 'none'), ('html', 'html'), ('htm', 'htm'), ('js', 'js'), ('css', 'css'), ('json', 'json'), ('xml', 'xml'), ('jpg', 'jpg'), ('jpeg', 'jpeg'), ('png', 'png'), ('gif', 'gif'), ('svg', 'svg'), ('ico', 'ico'), ('pdf', 'pdf'), ('doc', 'doc'), ('docx', 'docx'), ('xls', 'xls'), ('xlsx', 'xlsx'), ('ppt', 'ppt'), ('pptx', 'pptx'), ('txt', 'txt'), ('csv', 'csv'), ('zip', 'zip'), ('rar', 'rar'), ('7z', '7z'), ('tar', 'tar'), ('gz', 'gz'), ('exe', 'exe'), ('apk', 'apk'), ('mp3', 'mp3'), ('mp4', 'mp4'), ('mov', 'mov'), ('avi', 'avi'), ('mkv', 'mkv'), ('webm', 'webm'), ('wav', 'wav'), ('flac', 'flac'), ('ogg', 'ogg'), ('log', 'log'), ('sql', 'sql'), ('db', 'db'), ('conf', 'conf'), ('ini', 'ini'), ('yml', 'yml'), ('yaml', 'yaml'), ('env', 'env')], default='none', max_length=150)),
                ('body_hash', models.CharField(blank=True, max_length=300)),
                ('subdomain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset_monitor.discoversubdomain')),
            ],
            options={
                'verbose_name': 'URL',
                'verbose_name_plural': 'URLs',
            },
        ),
        migrations.CreateModel(
            name='UrlChanges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('label', models.CharField(choices=[('new', 'NEW'), ('available', 'AVAILABLE')], default='new', max_length=150)),
                ('old_body_hash', models.CharField(blank=True, max_length=300)),
                ('new_body_hash', models.CharField(blank=True, max_length=300)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='url_monitor.url')),
            ],
            options={
                'verbose_name': 'URL Change',
                'verbose_name_plural': 'URL Changes',
            },
        ),
    ]
