# Generated by Django 5.2.4 on 2025-08-28 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset_monitor', '0009_alter_tool_tool_name'),
        ('url_monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subdomainparameter',
            unique_together={('subdomain', 'parameter')},
        ),
    ]
