# Generated by Django 5.2.4 on 2025-08-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='injection_place',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='label',
            field=models.CharField(choices=[('new', 'NEW'), ('available', 'AVAILABLE')], default='new'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='method',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='parameter',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='reason_kind',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='status',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subdomainparameter',
            name='label',
            field=models.CharField(choices=[('new', 'NEW'), ('available', 'AVAILABLE')], default='new'),
        ),
        migrations.AlterField(
            model_name='subdomainparameter',
            name='parameter',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='url',
            name='body_hash',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='ext',
            field=models.CharField(choices=[('none', 'none'), ('html', '.html'), ('htm', '.htm'), ('xhtml', '.xhtml'), ('php', '.php'), ('asp', '.asp'), ('aspx', '.aspx'), ('jsp', '.jsp'), ('cgi', '.cgi'), ('pl', '.pl'), ('js', '.js'), ('ts', '.ts'), ('jsx', '.jsx'), ('tsx', '.tsx'), ('css', '.css'), ('scss', '.scss'), ('sass', '.sass'), ('less', '.less'), ('json', '.json'), ('xml', '.xml'), ('yaml', '.yaml'), ('yml', '.yml'), ('csv', '.csv'), ('txt', '.txt'), ('jpg', '.jpg'), ('jpeg', '.jpeg'), ('png', '.png'), ('gif', '.gif'), ('svg', '.svg'), ('webp', '.webp'), ('ico', '.ico'), ('bmp', '.bmp'), ('tiff', '.tiff'), ('heic', '.heic'), ('pdf', '.pdf'), ('doc', '.doc'), ('docx', '.docx'), ('xls', '.xls'), ('xlsx', '.xlsx'), ('ppt', '.ppt'), ('pptx', '.pptx'), ('odt', '.odt'), ('ods', '.ods'), ('odp', '.odp'), ('zip', '.zip'), ('rar', '.rar'), ('7z', '.7z'), ('tar', '.tar'), ('gz', '.gz'), ('bz2', '.bz2'), ('mp3', '.mp3'), ('wav', '.wav'), ('flac', '.flac'), ('ogg', '.ogg'), ('mp4', '.mp4'), ('mov', '.mov'), ('avi', '.avi'), ('mkv', '.mkv'), ('webm', '.webm'), ('exe', '.exe'), ('apk', '.apk'), ('bin', '.bin'), ('jar', '.jar'), ('sh', '.sh'), ('bat', '.bat'), ('sql', '.sql'), ('db', '.db'), ('sqlite', '.sqlite'), ('mdb', '.mdb'), ('conf', '.conf'), ('ini', '.ini'), ('env', '.env'), ('log', '.log'), ('cfg', '.cfg'), ('toml', '.toml'), ('lock', '.lock'), ('crt', '.crt'), ('key', '.key')], default='none'),
        ),
        migrations.AlterField(
            model_name='url',
            name='label',
            field=models.CharField(choices=[('new', 'NEW'), ('available', 'AVAILABLE')], default='new'),
        ),
        migrations.AlterField(
            model_name='url',
            name='path',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='query',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='status',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='url',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='urlchanges',
            name='body_hash_change',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='urlchanges',
            name='ext',
            field=models.CharField(choices=[('none', 'none'), ('html', '.html'), ('htm', '.htm'), ('xhtml', '.xhtml'), ('php', '.php'), ('asp', '.asp'), ('aspx', '.aspx'), ('jsp', '.jsp'), ('cgi', '.cgi'), ('pl', '.pl'), ('js', '.js'), ('ts', '.ts'), ('jsx', '.jsx'), ('tsx', '.tsx'), ('css', '.css'), ('scss', '.scss'), ('sass', '.sass'), ('less', '.less'), ('json', '.json'), ('xml', '.xml'), ('yaml', '.yaml'), ('yml', '.yml'), ('csv', '.csv'), ('txt', '.txt'), ('jpg', '.jpg'), ('jpeg', '.jpeg'), ('png', '.png'), ('gif', '.gif'), ('svg', '.svg'), ('webp', '.webp'), ('ico', '.ico'), ('bmp', '.bmp'), ('tiff', '.tiff'), ('heic', '.heic'), ('pdf', '.pdf'), ('doc', '.doc'), ('docx', '.docx'), ('xls', '.xls'), ('xlsx', '.xlsx'), ('ppt', '.ppt'), ('pptx', '.pptx'), ('odt', '.odt'), ('ods', '.ods'), ('odp', '.odp'), ('zip', '.zip'), ('rar', '.rar'), ('7z', '.7z'), ('tar', '.tar'), ('gz', '.gz'), ('bz2', '.bz2'), ('mp3', '.mp3'), ('wav', '.wav'), ('flac', '.flac'), ('ogg', '.ogg'), ('mp4', '.mp4'), ('mov', '.mov'), ('avi', '.avi'), ('mkv', '.mkv'), ('webm', '.webm'), ('exe', '.exe'), ('apk', '.apk'), ('bin', '.bin'), ('jar', '.jar'), ('sh', '.sh'), ('bat', '.bat'), ('sql', '.sql'), ('db', '.db'), ('sqlite', '.sqlite'), ('mdb', '.mdb'), ('conf', '.conf'), ('ini', '.ini'), ('env', '.env'), ('log', '.log'), ('cfg', '.cfg'), ('toml', '.toml'), ('lock', '.lock'), ('crt', '.crt'), ('key', '.key')], default='none'),
        ),
        migrations.AlterField(
            model_name='urlchanges',
            name='label',
            field=models.CharField(choices=[('new', 'NEW'), ('available', 'AVAILABLE')], default='new'),
        ),
        migrations.AlterField(
            model_name='urlchanges',
            name='query_change',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='urlchanges',
            name='status_change',
            field=models.CharField(blank=True, null=True),
        ),
    ]
