# Generated by Django 5.2.4 on 2025-08-20 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_monitor', '0002_alter_url_path_alter_url_query'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('method', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('parameter', models.CharField(blank=True, max_length=1000, null=True)),
                ('reason_kind', models.CharField(blank=True, max_length=100, null=True)),
                ('injection_place', models.CharField(blank=True, max_length=1000, null=True)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='url_monitor.url')),
            ],
            options={
                'verbose_name': 'Parameter',
                'verbose_name_plural': 'Parameters',
            },
        ),
    ]
