# Generated by Django 5.2.4 on 2025-08-17 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_monitor', '0002_alter_url_body_hash'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urlchanges',
            old_name='new_body_hash',
            new_name='body_hash_change',
        ),
        migrations.RenameField(
            model_name='urlchanges',
            old_name='path',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='urlchanges',
            name='old_body_hash',
        ),
        migrations.AddField(
            model_name='urlchanges',
            name='ext',
            field=models.CharField(choices=[('none', 'none'), ('html', '.html'), ('htm', '.htm'), ('xhtml', '.xhtml'), ('php', '.php'), ('asp', '.asp'), ('aspx', '.aspx'), ('jsp', '.jsp'), ('cgi', '.cgi'), ('pl', '.pl'), ('js', '.js'), ('ts', '.ts'), ('jsx', '.jsx'), ('tsx', '.tsx'), ('css', '.css'), ('scss', '.scss'), ('sass', '.sass'), ('less', '.less'), ('json', '.json'), ('xml', '.xml'), ('yaml', '.yaml'), ('yml', '.yml'), ('csv', '.csv'), ('txt', '.txt'), ('jpg', '.jpg'), ('jpeg', '.jpeg'), ('png', '.png'), ('gif', '.gif'), ('svg', '.svg'), ('webp', '.webp'), ('ico', '.ico'), ('bmp', '.bmp'), ('tiff', '.tiff'), ('heic', '.heic'), ('pdf', '.pdf'), ('doc', '.doc'), ('docx', '.docx'), ('xls', '.xls'), ('xlsx', '.xlsx'), ('ppt', '.ppt'), ('pptx', '.pptx'), ('odt', '.odt'), ('ods', '.ods'), ('odp', '.odp'), ('zip', '.zip'), ('rar', '.rar'), ('7z', '.7z'), ('tar', '.tar'), ('gz', '.gz'), ('bz2', '.bz2'), ('mp3', '.mp3'), ('wav', '.wav'), ('flac', '.flac'), ('ogg', '.ogg'), ('mp4', '.mp4'), ('mov', '.mov'), ('avi', '.avi'), ('mkv', '.mkv'), ('webm', '.webm'), ('exe', '.exe'), ('apk', '.apk'), ('bin', '.bin'), ('jar', '.jar'), ('sh', '.sh'), ('bat', '.bat'), ('sql', '.sql'), ('db', '.db'), ('sqlite', '.sqlite'), ('mdb', '.mdb'), ('conf', '.conf'), ('ini', '.ini'), ('env', '.env'), ('log', '.log'), ('cfg', '.cfg'), ('toml', '.toml'), ('lock', '.lock'), ('crt', '.crt'), ('key', '.key')], default='none', max_length=150),
        ),
        migrations.AddField(
            model_name='urlchanges',
            name='path_change',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='urlchanges',
            name='query_change',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
