# Generated by Django 5.2.4 on 2025-08-17 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_monitor', '0003_rename_new_body_hash_urlchanges_body_hash_change_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlchanges',
            name='path_change',
        ),
    ]
