# Generated by Django 5.2.4 on 2025-08-20 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_monitor', '0003_parameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='label',
            field=models.CharField(choices=[('new', 'NEW'), ('available', 'AVAILABLE')], default='new', max_length=150),
        ),
    ]
