# Generated by Django 5.2.4 on 2025-09-05 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_monitor', '0003_alter_url_options_newurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='newurl',
            name='tool',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='url',
            name='tool',
            field=models.CharField(blank=True, null=True),
        ),
    ]
