# Generated by Django 5.2.4 on 2025-08-17 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_monitor', '0004_remove_urlchanges_path_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlchanges',
            name='body_hash_change',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
