# Generated by Django 5.2.4 on 2025-09-05 08:33

import asset_monitor.models
import url_monitor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_monitor', '0004_newurl_tool_url_tool'),
    ]

    operations = [
        migrations.AddField(
            model_name='newurl',
            name='own_urls',
            field=models.FileField(blank=True, null=True, upload_to=url_monitor.models.user_urls_upload_path, validators=[asset_monitor.models.validate_wordlist_file]),
        ),
        migrations.AddField(
            model_name='url',
            name='own_urls',
            field=models.FileField(blank=True, null=True, upload_to=url_monitor.models.user_urls_upload_path, validators=[asset_monitor.models.validate_wordlist_file]),
        ),
    ]
