# Generated by Django 5.2.4 on 2025-09-08 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_monitor', '0005_newurl_own_urls_url_own_urls'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parameter',
            options={'verbose_name': 'URL Parameters', 'verbose_name_plural': 'URLs Parameters'},
        ),
    ]
