# Generated by Django 5.2.4 on 2025-08-17 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_monitor', '0005_alter_urlchanges_body_hash_change'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlchanges',
            name='query_change',
        ),
    ]
