# Generated by Django 5.2.4 on 2025-08-20 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_monitor', '0006_urlchanges_status_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlchanges',
            name='query_change',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
