# Generated by Django 5.2.4 on 2025-09-09 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_monitor', '0006_alter_parameter_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='newurl',
            name='diff_type',
            field=models.CharField(blank=True, null=True),
        ),
    ]
