# Generated by Django 5.2.4 on 2025-09-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_monitor', '0007_newurl_diff_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdomainparameter',
            name='parameter',
            field=models.CharField(blank=True, null=True),
        ),
    ]
