# Generated by Django 5.2.4 on 2025-08-20 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_monitor', '0006_alter_discoversubdomain_options'),
        ('url_monitor', '0007_urlchanges_query_change'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubdomainParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('parameter', models.CharField(max_length=500)),
                ('label', models.CharField(choices=[('new', 'NEW'), ('available', 'AVAILABLE')], default='new', max_length=150)),
                ('subdomain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset_monitor.discoversubdomain')),
            ],
            options={
                'verbose_name': 'Subdomain Parameter',
                'verbose_name_plural': 'Subdomain Parameters',
            },
        ),
    ]
