# Generated by Django 5.2.4 on 2025-09-14 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_monitor', '0008_alter_subdomainparameter_parameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='newurl',
            name='base64_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='url',
            name='base64_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='urlchanges',
            name='base64_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
