# Generated by Django 5.2.4 on 2025-09-15 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_monitor', '0009_newurl_base64_content_url_base64_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urlchanges',
            old_name='base64_content',
            new_name='base64_content_change',
        ),
    ]
