# Generated by Django 5.2.1 on 2025-05-27 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tools', '0002_alter_tool_demo_video_file_alter_tool_upload_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TechniquesCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='techniques.techniquescategory')),
            ],
            options={
                'verbose_name': 'Technique Category',
                'verbose_name_plural': 'Technique Categories',
            },
        ),
        migrations.CreateModel(
            name='Techniques',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('content', models.TextField(max_length=2000)),
                ('preview_text', models.TextField(max_length=500)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('is_free', models.BooleanField(default=False)),
                ('purchase_count', models.PositiveIntegerField(default=0)),
                ('is_public', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], help_text='The difficulty level of the technique.', max_length=50)),
                ('proof_of_concept', models.TextField(blank=True, help_text='Proof of concept or example of the technique in action.', null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('related_tools', models.ManyToManyField(blank=True, help_text='Tools commonly used with this technique.', related_name='techniques', to='tools.tool')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='techniques.techniquescategory')),
            ],
            options={
                'verbose_name': 'Technique',
                'verbose_name_plural': 'Techniques',
            },
        ),
    ]
