# Generated by Django 5.1.3 on 2025-05-31 20:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ZeroDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(help_text='Detailed description of the zero-day vulnerability.')),
                ('affected_products', models.TextField(blank=True, help_text='List of affected software/hardware versions.', null=True)),
                ('severity', models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=20, null=True)),
                ('exploit_vector', models.CharField(blank=True, help_text='E.g., Remote, Local, Web-based', max_length=100, null=True)),
                ('impact', models.CharField(blank=True, help_text='E.g., RCE, LFI, SQLi, PrivEsc', max_length=100, null=True)),
                ('cve_reference', models.CharField(blank=True, help_text='Optional CVE reference if it exists.', max_length=50, null=True)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Indicates whether the zero-day has been verified.')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zerodays', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Zero Day',
                'verbose_name_plural': 'Zero Days',
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='ZeroDayAuction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('starting_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('current_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField()),
                ('last_bid_time', models.DateTimeField(blank=True, help_text='Last time a bid was placed.', null=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zeroday_auctions', to=settings.AUTH_USER_MODEL)),
                ('zeroday', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auction', to='zerodays.zeroday')),
            ],
            options={
                'verbose_name': 'Zero Day Auction',
                'verbose_name_plural': 'Zero Day Auctions',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='ZeroDayBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_winning', models.BooleanField(default=False)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zerodays.zerodayauction')),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Zero Day Bid',
                'verbose_name_plural': 'Zero Day Bids',
            },
        ),
        migrations.CreateModel(
            name='ZeroDayCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='zerodays.zerodaycategory')),
            ],
            options={
                'verbose_name': 'ZeroDay Category',
                'verbose_name_plural': 'ZeroDay Categories',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='zeroday',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zerodays.zerodaycategory'),
        ),
        migrations.CreateModel(
            name='ZeroDayDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('final_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('completed_at', models.DateField()),
                ('deal_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('disputed', 'Disputed')], default='pending', max_length=20)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='zerodays.zerodayauction')),
                ('buyer_bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal', to='zerodays.zerodaybid')),
            ],
            options={
                'verbose_name': 'ZeroDay Deal',
                'verbose_name_plural': 'ZeroDay Deals',
                'ordering': ['-completed_at'],
            },
        ),
    ]
