# Generated by Django 5.2.1 on 2025-05-27 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writeups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writeup',
            name='short_description',
        ),
        migrations.AddField(
            model_name='writeup',
            name='read_time',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='writeup',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='writeup',
            name='content',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='writeup',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='writeup',
            name='preview_text',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='writeup',
            name='slug',
            field=models.SlugField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='writeup',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.CreateModel(
            name='WriteUpAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='writeups/attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('writeup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='writeups.writeup')),
            ],
        ),
    ]
