# Generated by Django 5.2.4 on 2025-08-16 17:38

import asset_monitor.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoverSubdomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('subdomain', models.CharField(blank=True, max_length=300, null=True, unique=True)),
                ('label', models.CharField(choices=[('new', 'NEW'), ('available', 'AVAILABLE')], default='new', max_length=50)),
            ],
            options={
                'verbose_name': 'Discovered Subdomain',
                'verbose_name_plural': 'Discovered Subdomains',
            },
        ),
        migrations.CreateModel(
            name='Ports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.CharField(blank=True, choices=[('80', '80'), ('8080', '8080'), ('8081', '8081'), ('8880', '8880'), ('2052', '2052'), ('2082', '2082'), ('2086', '2086'), ('2095', '2095'), ('443', '443'), ('2053', '2053'), ('2087', '2087'), ('2096', '2096'), ('8443', '8443'), ('10443', '10443')], max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Port',
                'verbose_name_plural': 'Ports',
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(choices=[('owned', 'Owned'), ('amass', 'Amass'), ('subfinder', 'Subfinder'), ('dns_bruteforce', 'DNS Bruteforce'), ('httpx', 'Httpx'), ('wabackurls', 'Wabackurls'), ('crt.sh', 'CRT.sh')], default='subfinder', max_length=120)),
            ],
            options={
                'verbose_name': 'Tool',
                'verbose_name_plural': 'Tools',
            },
        ),
        migrations.CreateModel(
            name='AssetWatcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notify', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=150)),
                ('dns_bruteforce_static_wordlist', models.FileField(blank=True, default=asset_monitor.models.default_wordlist_path, null=True, upload_to=asset_monitor.models.user_static_wordlist_upload_path, validators=[asset_monitor.models.validate_wordlist_file])),
                ('dns_bruteforce_dynamic_wordlist', models.FileField(blank=True, default=asset_monitor.models.default_wordlist_path, null=True, upload_to=asset_monitor.models.user_dynamic_wordlist_upload_path, validators=[asset_monitor.models.validate_wordlist_file])),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asset Watcher',
                'verbose_name_plural': 'Asset Watchers',
            },
        ),
        migrations.CreateModel(
            name='SubdomainHttpx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('httpx_result', models.URLField(blank=True, max_length=300, null=True)),
                ('status_code', models.CharField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('server', models.CharField(blank=True, max_length=300, null=True)),
                ('technologies', models.CharField(blank=True, max_length=900)),
                ('ip_address', models.CharField(blank=True, max_length=120, null=True)),
                ('port', models.CharField(blank=True, null=True)),
                ('content_type', models.CharField(blank=True, max_length=300, null=True)),
                ('line_count', models.CharField(blank=True, null=True)),
                ('a_records', models.CharField(blank=True)),
                ('body_hash', models.CharField(blank=True, max_length=200, null=True)),
                ('header_hash', models.CharField(blank=True, max_length=200, null=True)),
                ('has_cdn', models.CharField(blank=True, default='False', max_length=10, null=True)),
                ('label', models.CharField(choices=[('new', 'NEW'), ('available', 'AVAILABLE')], default='new')),
                ('discovered_subdomain', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='asset_monitor.discoversubdomain')),
            ],
            options={
                'verbose_name': 'Subdomain Httpx',
                'verbose_name_plural': 'Subdomain Httpxes',
            },
        ),
        migrations.CreateModel(
            name='SubdomainHttpxChanges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('httpx_result_change', models.CharField(blank=True, null=True)),
                ('status_code_change', models.CharField(blank=True, null=True)),
                ('title_change', models.CharField(blank=True, max_length=500, null=True)),
                ('server_change', models.CharField(blank=True, null=True)),
                ('technologies_change', models.CharField(blank=True)),
                ('ip_address_change', models.CharField(blank=True, null=True)),
                ('port_change', models.CharField(blank=True, null=True)),
                ('content_type_change', models.CharField(blank=True, null=True)),
                ('line_count_change', models.CharField(blank=True, null=True)),
                ('a_records_change', models.CharField(blank=True)),
                ('body_hash_change', models.CharField(blank=True, null=True)),
                ('header_hash_change', models.CharField(blank=True, null=True)),
                ('has_cdn_change', models.CharField(blank=True, null=True)),
                ('label', models.CharField(choices=[('new', 'NEW'), ('available', 'AVAILABLE')], default='new')),
                ('discovered_subdomain', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='asset_monitor.discoversubdomain')),
            ],
            options={
                'verbose_name': 'Subdomain Httpx Changes',
                'verbose_name_plural': 'Subdomain Httpxes Changes',
            },
        ),
        migrations.AddField(
            model_name='discoversubdomain',
            name='tool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asset_monitor.tool'),
        ),
        migrations.CreateModel(
            name='WatchedWildcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('wildcard', models.CharField(blank=True, max_length=300, null=True, unique=True)),
                ('own_subdomains', models.FileField(blank=True, null=True, upload_to=asset_monitor.models.user_subdomains_upload_path, validators=[asset_monitor.models.validate_wordlist_file])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=150)),
                ('tools', models.ManyToManyField(to='asset_monitor.tool')),
                ('watcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wildcards', to='asset_monitor.assetwatcher')),
            ],
            options={
                'verbose_name': 'Watcher Wildcard',
                'verbose_name_plural': 'Watcher Wildcards',
            },
        ),
        migrations.AddField(
            model_name='discoversubdomain',
            name='wildcard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdomains', to='asset_monitor.watchedwildcard'),
        ),
        migrations.CreateModel(
            name='WatcherCIDR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('cidr', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='new', max_length=50)),
                ('ports', models.ManyToManyField(to='asset_monitor.ports')),
                ('watcher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cidrs', to='asset_monitor.assetwatcher')),
            ],
            options={
                'verbose_name': 'Watcher CIDR',
                'verbose_name_plural': 'Watcher CIDRs',
            },
        ),
        migrations.CreateModel(
            name='DiscoverdServicesAlive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('service', models.CharField(blank=True, max_length=100, null=True)),
                ('status_code', models.CharField(blank=True, max_length=100, null=True)),
                ('label', models.CharField(choices=[('new', 'NEW'), ('available', 'AVAILABLE')], default='available')),
                ('watcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discoverd_services_alive', to='asset_monitor.watchercidr')),
            ],
            options={
                'verbose_name': 'Discovered Service Alive',
                'verbose_name_plural': 'Discovered Services Alive',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DiscoverdServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ip', models.CharField(blank=True, max_length=20, null=True)),
                ('port', models.CharField(blank=True, max_length=10, null=True)),
                ('label', models.CharField(choices=[('new', 'NEW'), ('available', 'AVAILABLE')], default='available')),
                ('has_change', models.BooleanField(default=False)),
                ('watcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discoverd_services', to='asset_monitor.watchercidr')),
            ],
            options={
                'verbose_name': 'Discoverd Service',
                'verbose_name_plural': 'Discovered Services',
            },
        ),
    ]
