# Generated by Django 5.2.4 on 2025-08-16 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset_monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subdomainhttpx',
            options={'verbose_name': 'Subdomain HTTPX', 'verbose_name_plural': 'Subdomains HTTPX'},
        ),
    ]
