# Generated by Django 5.2.4 on 2025-08-17 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_monitor', '0002_alter_subdomainhttpx_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestHeaders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('header', models.CharField(blank=True, max_length=5000, null=True)),
                ('asset_watcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset_monitor.assetwatcher')),
            ],
            options={
                'verbose_name': 'Request Header',
                'verbose_name_plural': 'Request Headers',
            },
        ),
    ]
