# Generated by Django 5.2.4 on 2025-08-18 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_monitor', '0004_alter_requestheaders_asset_watcher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestheaders',
            name='asset_watcher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset_monitor.discoversubdomain'),
        ),
    ]
