# Generated by Django 5.2.4 on 2025-08-20 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset_monitor', '0005_alter_requestheaders_asset_watcher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discoversubdomain',
            options={'ordering': ['label'], 'verbose_name': 'Discovered Subdomain', 'verbose_name_plural': 'Discovered Subdomains'},
        ),
    ]
