# Generated by Django 5.2.4 on 2025-08-23 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_monitor', '0006_alter_discoversubdomain_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='tool_name',
            field=models.CharField(choices=[('owned', 'Owned'), ('amass', 'Amass'), ('subfinder', 'Subfinder'), ('dns_bruteforce', 'DNS Bruteforce'), ('httpx', 'HTTPX'), ('wabackurls', 'Wabackurls'), ('crt.sh', 'CRT.sh')], default='subfinder', max_length=120),
        ),
    ]
