# Generated by Django 5.2.4 on 2025-08-25 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset_monitor', '0007_alter_tool_tool_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subdomainhttpxchanges',
            options={'verbose_name': 'Subdomain HTTPX Changes', 'verbose_name_plural': 'Subdomains HTTPX Changes'},
        ),
    ]
