# Generated by Django 5.2.4 on 2025-08-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_monitor', '0008_alter_subdomainhttpxchanges_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='tool_name',
            field=models.CharField(choices=[('owned', 'Owned'), ('amass', 'Amass'), ('subfinder', 'Subfinder'), ('dns_bruteforce', 'DNS Bruteforce'), ('httpx', 'HTTPX'), ('wabackurls', 'Wabackurls'), ('crt.sh', 'CRT.sh'), ('narrow_monitor', 'Narrow Monitor')], default='subfinder', max_length=120),
        ),
    ]
