# Generated by Django 5.2.4 on 2025-09-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_monitor', '0009_alter_tool_tool_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='tool_name',
            field=models.CharField(choices=[('owned', 'Owned'), ('amass', 'Amass'), ('subfinder', 'Subfinder'), ('dns_bruteforce', 'DNS Bruteforce'), ('httpx', 'HTTPX'), ('wabackurls', 'Wabackurls'), ('crt.sh', 'CRT.sh'), ('url_monitor', 'URL Monitor'), ('vulnerabilities_monitor', 'Vulnerabilities Monitor')], default='subfinder', max_length=120),
        ),
    ]
