# Generated by Django 5.2.4 on 2025-09-04 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_monitor', '0010_alter_tool_tool_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchedwildcard',
            name='tools',
            field=models.ManyToManyField(help_text='Accure', to='asset_monitor.tool'),
        ),
    ]
