# Generated by Django 5.2.4 on 2025-09-04 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_monitor', '0011_alter_watchedwildcard_tools'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='tool_name',
            field=models.CharField(choices=[('owned', 'Owned'), ('amass', 'Amass'), ('subfinder', 'Subfinder'), ('dns_bruteforce', 'DNS Bruteforce'), ('httpx', 'HTTPX'), ('wabackurls', 'Wabackurls'), ('crt.sh', 'CRT.sh'), ('daily_narrow_monitoring', 'Daily Narrow Monitoring'), ('daily_vulnerabilities_monitor', 'Daily Vulnerabilities Monitoring')], default='subfinder', max_length=120),
        ),
    ]
