# Generated by Django 5.2.1 on 2025-05-27 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoverdProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('type', models.CharField(choices=[('vdp', 'VDP'), ('rdp', 'RDP'), ('others', 'OTHERS')], max_length=100)),
                ('discovered_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(choices=[('new', 'NEW'), ('available', 'AVAILABLE')], default='available', max_length=100)),
            ],
            options={
                'verbose_name': 'Discoverd Program',
                'verbose_name_plural': 'Discoverd Programs',
                'ordering': ['-discovered_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgramWatcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('platform_name', models.CharField(max_length=150)),
                ('platform_url', models.URLField()),
                ('check_time', models.IntegerField(default=12)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='watchers/programwatcher/logo/')),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=150)),
                ('notify', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Program Watcher',
                'verbose_name_plural': 'Program Watchers',
            },
        ),
        migrations.CreateModel(
            name='DiscoverdScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=500)),
                ('label', models.CharField(choices=[('new', 'NEW'), ('available', 'AVAILABLE')], default='available', max_length=100)),
                ('type', models.CharField(choices=[('ai_model', 'AI Model'), ('web', 'Web Application'), ('wildcard', 'Wildcard Domain (*.example.com)'), ('mobile', 'Mobile Application (iOS / Android)'), ('api', 'API (REST / GraphQL)'), ('web3', 'Web3 / Smart Contract / dApp'), ('desktop', 'Desktop / Thick Client'), ('iot', 'IoT / Hardware Device'), ('cloud', 'Cloud Infrastructure (AWS, GCP, etc.)'), ('code', 'Source Code / Repository'), ('infrastructure', 'External Infrastructure (CIDR / DNS / Mail Servers)'), ('physical', 'Physical Security'), ('third_party', 'Third-Party Hosted Apps'), ('others', 'Others')], max_length=150)),
                ('scope_type', models.CharField(blank=True, choices=[('in_scope', 'In Scope'), ('out_of_scope', 'Out Of Scope')], max_length=100, null=True)),
                ('discovered_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs_monitor.discoverdprogram')),
            ],
            options={
                'verbose_name': 'Discoverd Scope',
                'verbose_name_plural': 'Discoverd Scopes',
            },
        ),
        migrations.AddField(
            model_name='discoverdprogram',
            name='watcher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='watcher_program', to='programs_monitor.programwatcher'),
        ),
        migrations.AlterUniqueTogether(
            name='discoverdprogram',
            unique_together={('watcher', 'name')},
        ),
    ]
