# Generated by Django 5.2.1 on 2025-06-01 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs_monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programwatcher',
            name='platform_name',
            field=models.CharField(max_length=200),
        ),
    ]
