# Generated by Django 5.2.1 on 2025-05-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='demo_video_file',
            field=models.FileField(blank=True, null=True, upload_to='tools/tool/demo/videos/'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='upload_file',
            field=models.FileField(blank=True, null=True, upload_to='tools/tool/files/'),
        ),
        migrations.AlterField(
            model_name='toolimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='tool/toolimage/images/'),
        ),
    ]
